Fix to ComponentArmour.dat issue & Remaining Crashes
Project-Path-of-Exile-Wiki/PyPoE pull request #22
Opened 2021-10-26 04:47 UTC by angelic-knight

This fixes #20 and fixes #23
Figured out how to make pull requests :)

2021-10-26 05:40 UTC, angelic-knight commented
The second commit in here fixes #23

2021-10-28 12:18 UTC, pm5k requested changes

2021-10-28 12:18 UTC, pm5k commented on PyPoE/cli/exporter/util.py
> +        return path
Can just do:

```py
    path = path.replace('\"','&quot;')
    if re.match('[a-zA-Z]:.*', path):
        # no need to store this expression into a var you're returning in the next line
        #  and nowhere else in this particular scope.
        return path[:2] + re.sub(r':', '_', path[2:])
    else:
        return path 
```

2021-10-28 13:44 UTC, angelic-knight commented on PyPoE/cli/exporter/util.py
> +        return path
True and reasonable.
Updated the PR to not store it in path unnecessarily.

2021-11-01 14:05 UTC, merged