Updates to Mastery Exporting
Project-Path-of-Exile-Wiki/PyPoE pull request #64
Opened 2021-12-02 04:09 UTC by angelic-knight

# Abstract

Adds a Name field to Mastery Groups, which is pulled from passive skills that let you allocate the masteries.

# Action Taken

On the wiki, there was need for a user-facing name for Mastery Groups in addition to the internal ID (which was already readable, but never had spaces and would differ from the in-game wording in some cases.
I've updated the mastery export to determine those names using the skill tree and to save them in the wiki exports.

# Caveats

The mastery export is now dependent on the passive tree data structure.
This is better than being dependent on a hard-coded mapping of mastery groups to names.

# FAO

@pm5k @Journeytojah @acbeaumo

2021-12-11 12:03 UTC, pm5k requested changes
Just two tiny changes please.

2021-12-11 12:03 UTC, pm5k commented on PyPoE/cli/exporter/wiki/parsers/masteries.py
> +            if not passive['MasteryGroup'] is None:
This is awfully nitpicky of me, but it does not read as nice as `if passive['MasteryGroup'] is not None:..`

2021-12-11 12:03 UTC, pm5k commented on PyPoE/cli/exporter/wiki/parsers/masteries.py
> +                out_file='mastery_group_%s.txt' % data['name'],
```py
out_file='mastery_group_%s.txt' % data['name'],

# into:

out_file=f"mastery_group_{data['name']}s.txt",
```

2021-12-11 17:01 UTC, angelic-knight commented on PyPoE/cli/exporter/wiki/parsers/masteries.py
> +            if not passive['MasteryGroup'] is None:
This has been resolved.
Same as with the other place I did this - thought that the more readable way wouldn't work for some reason.

2021-12-11 17:01 UTC, angelic-knight commented on PyPoE/cli/exporter/wiki/parsers/masteries.py
> +                out_file='mastery_group_%s.txt' % data['name'],
Cleaned this up.

2022-02-07 15:12 UTC, pm5k approved these changes

2022-02-07 15:12 UTC, merged